/**
 * EV comparison dataset.
 *
 * Figures are manufacturer / WLTP claims gathered from public sources
 * (manufacturer sites & brochures, EV-Database, EVKX, zecar, CarExpert) as of
 * 2025. Prices are indicative Australian RRP (AUD, before on-road costs) so
 * every model can be compared on a like-for-like basis; local pricing, range,
 * trim names and standard/optional equipment vary by market. Verify before
 * purchase. Where a feature is trim- or option-dependent it is marked
 * "Optional".
 *
 * `better` tells the UI which direction is "best" for numeric highlighting:
 *   'high' -> larger value wins, 'low' -> smaller value wins, null -> no winner.
 */

const CURRENCY = "AUD";

const SPEC_GROUPS = [
  {
    title: "Pricing & Positioning",
    rows: [
      { key: "price", label: "Indicative price (RRP)", unit: CURRENCY, better: "low", format: "currency" },
      { key: "segment", label: "Segment", better: null },
      { key: "bodyStyle", label: "Body style", better: null },
      { key: "trim", label: "Trim / grade", better: null },
    ],
  },
  {
    title: "Performance",
    rows: [
      { key: "power", label: "Peak power", unit: "kW", better: "high" },
      { key: "powerHp", label: "Peak power", unit: "hp", better: "high" },
      { key: "torque", label: "Peak torque", unit: "Nm", better: "high" },
      { key: "accel", label: "0–100 km/h", unit: "s", better: "low" },
      { key: "topSpeed", label: "Top speed", unit: "km/h", better: "high" },
      { key: "drive", label: "Drivetrain", better: null, hl: "drive" },
    ],
  },
  {
    title: "Battery, Range & Charging",
    rows: [
      { key: "rangeWltp", label: "Range (WLTP)", unit: "km", better: "high" },
      { key: "batteryUsable", label: "Usable battery", unit: "kWh", better: "high" },
      { key: "batteryType", label: "Battery chemistry", better: null },
      { key: "architecture", label: "Electrical architecture", better: null, hl: "num" },
      { key: "dcMax", label: "Max DC charging", unit: "kW", better: "high" },
      { key: "dcTime", label: "DC 10–80%", unit: "min", better: "low" },
      { key: "acMax", label: "Max AC charging", unit: "kW", better: "high" },
      { key: "efficiency", label: "Efficiency (WLTP)", unit: "kWh/100km", better: "low" },
      { key: "heatPump", label: "Heat pump", better: null, hl: "feature" },
      { key: "v2l", label: "Vehicle-to-load (V2L)", better: null, hl: "feature" },
    ],
  },
  {
    title: "Dimensions & Practicality",
    rows: [
      { key: "length", label: "Length", unit: "mm", better: null },
      { key: "width", label: "Width (excl. mirrors)", unit: "mm", better: null },
      { key: "height", label: "Height", unit: "mm", better: null },
      { key: "wheelbase", label: "Wheelbase", unit: "mm", better: "high" },
      { key: "boot", label: "Boot (rear)", unit: "L", better: "high" },
      { key: "bootMax", label: "Boot (seats folded)", unit: "L", better: "high" },
      { key: "frunk", label: "Frunk", unit: "L", better: "high" },
      { key: "seats", label: "Seats", better: null },
      { key: "kerbWeight", label: "Kerb weight", unit: "kg", better: "low" },
      { key: "towing", label: "Towing (braked)", unit: "kg", better: "high" },
      { key: "wheels", label: "Wheels", better: null },
    ],
  },
  {
    title: "Chassis & Suspension",
    rows: [
      { key: "suspensionFront", label: "Front suspension", better: null, hl: "suspension" },
      { key: "suspensionRear", label: "Rear suspension", better: null, hl: "suspension" },
      { key: "adaptiveDamping", label: "Adaptive damping", better: null, hl: "feature" },
      { key: "airSuspension", label: "Air suspension", better: null, hl: "feature" },
    ],
  },
  {
    title: "Comfort & Interior",
    rows: [
      { key: "seatMaterial", label: "Seat material", better: null, hl: "material" },
      { key: "seatComfort", label: "Front seats (heat/vent/massage)", better: null, hl: "comfort" },
      { key: "rearSeatHeat", label: "Rear seat heating", better: null, hl: "feature" },
      { key: "rearSeatVent", label: "Rear seat ventilation", better: null, hl: "feature" },
      { key: "steeringHeat", label: "Heated steering wheel", better: null, hl: "feature" },
      { key: "wirelessCharge", label: "Wireless phone charging", better: null, hl: "feature" },
      { key: "doorHandles", label: "Door handles", better: null, hl: "handles" },
      { key: "ambient", label: "Ambient lighting", better: null, hl: "feature" },
      { key: "roof", label: "Roof", better: null, hl: "roof" },
    ],
  },
  {
    title: "Infotainment",
    rows: [
      { key: "display", label: "Central display", better: null, hl: "num" },
      { key: "cluster", label: "Driver display", better: null, hl: "num" },
      { key: "headUp", label: "Head-up display", better: null, hl: "feature" },
      { key: "audio", label: "Audio system", better: null, hl: "num" },
    ],
  },
  {
    title: "Safety & Driver Assistance",
    rows: [
      { key: "ncap", label: "Safety rating (NCAP)", better: null, hl: "num" },
      { key: "airbags", label: "Airbags", better: null, hl: "num" },
      { key: "aeb", label: "Autonomous emergency braking", better: null, hl: "feature" },
      { key: "adaptiveCruise", label: "Adaptive cruise control", better: null, hl: "feature" },
      { key: "laneKeep", label: "Lane-keep assist", better: null, hl: "feature" },
      { key: "blindSpot", label: "Blind-spot monitoring", better: null, hl: "feature" },
      { key: "camera360", label: "360° camera", better: null, hl: "feature" },
      { key: "parkAssist", label: "Parking assist", better: null, hl: "feature" },
      { key: "driverMonitor", label: "Driver attention monitor", better: null, hl: "feature" },
      { key: "adas", label: "Driver-assist suite", better: null },
    ],
  },
  {
    title: "Ownership",
    rows: [
      { key: "warranty", label: "Vehicle warranty", better: null, hl: "num" },
      { key: "batteryWarranty", label: "Battery warranty", better: null, hl: "maxnum" },
    ],
  },
];

const VEHICLES = [
  {
    id: "zeekr-7x-base",
    brand: "Zeekr",
    model: "7X",
    trimShort: "RWD (Base)",
    accent: "#2b7fff",
    highlight: "Value-focused long-range SUV on an 800V platform",
    specs: {
      price: 57900,
      segment: "Mid-size SUV",
      bodyStyle: "5-door SUV",
      trim: "Core RWD",
      power: 310,
      powerHp: 421,
      torque: 440,
      accel: 6.0,
      topSpeed: 210,
      drive: "Rear-wheel drive",
      rangeWltp: 480,
      batteryUsable: 71,
      batteryType: "NMC (lithium-ion)",
      architecture: "800 V",
      dcMax: 480,
      dcTime: 13,
      acMax: 22,
      efficiency: 17.8,
      heatPump: "Yes",
      v2l: "Yes (3.3 kW)",
      length: 4787,
      width: 1930,
      height: 1650,
      wheelbase: 2900,
      boot: 539,
      bootMax: 1978,
      frunk: 42,
      seats: 5,
      kerbWeight: 2380,
      towing: 2000,
      wheels: '19" alloy',
      suspensionFront: "Double wishbone",
      suspensionRear: "Multi-link (5-link)",
      adaptiveDamping: "No",
      airSuspension: "No",
      seatMaterial: "Textile & PU",
      seatComfort: "Heated (front)",
      rearSeatHeat: "No",
      rearSeatVent: "No",
      steeringHeat: "No",
      wirelessCharge: "Yes (dual 50W)",
      doorHandles: "Flush, powered e-latch",
      ambient: "Yes (RGB)",
      roof: "Panoramic glass + powered sunshade",
      display: '16" 3.5K mini-LED',
      cluster: '13" LCD instrument cluster',
      headUp: "No",
      audio: "Zeekr Sound 10-speaker",
      ncap: "5★ (Euro NCAP & ANCAP)",
      airbags: "7 airbags (incl. far-side)",
      aeb: "Standard",
      adaptiveCruise: "Standard (ACC + LCC)",
      laneKeep: "Standard",
      blindSpot: "Standard",
      camera360: "Standard",
      parkAssist: "Standard (auto park)",
      driverMonitor: "Yes (DMS)",
      adas: "Zeekr Assisted Drive (15 functions)",
      warranty: "Varies by market",
      batteryWarranty: "8 yr / 200,000 km",
    },
  },
  {
    id: "zeekr-7x-long-range",
    brand: "Zeekr",
    model: "7X",
    trimShort: "Long Range RWD",
    accent: "#1b6ef3",
    highlight: "Longest-range Zeekr — 615 km from 100 kWh on 800V",
    specs: {
      price: 63900,
      segment: "Mid-size SUV",
      bodyStyle: "5-door SUV",
      trim: "Long Range RWD",
      power: 310,
      powerHp: 421,
      torque: 440,
      accel: 6.0,
      topSpeed: 210,
      drive: "Rear-wheel drive",
      rangeWltp: 615,
      batteryUsable: 95,
      batteryType: "NMC (lithium-ion)",
      architecture: "800 V",
      dcMax: 480,
      dcTime: 16,
      acMax: 22,
      efficiency: 17.7,
      heatPump: "Yes",
      v2l: "Yes (3.3 kW)",
      length: 4787,
      width: 1930,
      height: 1650,
      wheelbase: 2900,
      boot: 539,
      bootMax: 1978,
      frunk: 42,
      seats: 5,
      kerbWeight: 2415,
      towing: 2000,
      wheels: '19" alloy',
      suspensionFront: "Double wishbone",
      suspensionRear: "Multi-link (5-link)",
      adaptiveDamping: "No",
      airSuspension: "No",
      seatMaterial: "Textile & PU",
      seatComfort: "Heated + ventilated + massage",
      rearSeatHeat: "Yes",
      rearSeatVent: "No",
      steeringHeat: "Yes",
      wirelessCharge: "Yes (dual 50W)",
      doorHandles: "Flush, powered e-latch",
      ambient: "Yes (RGB)",
      roof: "Panoramic glass + powered sunshade",
      display: '16" 3.5K mini-LED',
      cluster: '13" LCD instrument cluster',
      headUp: "Yes (36\" AR HUD)",
      audio: "Zeekr Sound Pro 21-spk (Dolby Atmos)",
      ncap: "5★ (Euro NCAP & ANCAP)",
      airbags: "7 airbags (incl. far-side)",
      aeb: "Standard",
      adaptiveCruise: "Standard (ACC + LCC)",
      laneKeep: "Standard",
      blindSpot: "Standard",
      camera360: "Standard",
      parkAssist: "Standard (auto park)",
      driverMonitor: "Yes (DMS)",
      adas: "Zeekr Assisted Drive (15 functions)",
      warranty: "Varies by market",
      batteryWarranty: "8 yr / 200,000 km",
    },
  },
  {
    id: "zeekr-7x-performance",
    brand: "Zeekr",
    model: "7X",
    trimShort: "Performance AWD",
    accent: "#0b3ea8",
    highlight: "Quickest here — 470 kW dual-motor with air suspension",
    specs: {
      price: 72900,
      segment: "Mid-size SUV",
      bodyStyle: "5-door SUV",
      trim: "Privilege AWD",
      power: 470,
      powerHp: 639,
      torque: 710,
      accel: 3.8,
      topSpeed: 210,
      drive: "All-wheel drive (dual motor)",
      rangeWltp: 543,
      batteryUsable: 95,
      batteryType: "NMC (CATL Qilin)",
      architecture: "800 V",
      dcMax: 480,
      dcTime: 16,
      acMax: 22,
      efficiency: 19.9,
      heatPump: "Yes",
      v2l: "Yes (3.3 kW)",
      length: 4787,
      width: 1930,
      height: 1650,
      wheelbase: 2900,
      boot: 539,
      bootMax: 1978,
      frunk: 42,
      seats: 5,
      kerbWeight: 2535,
      towing: 2000,
      wheels: '21" alloy',
      suspensionFront: "Double wishbone",
      suspensionRear: "Multi-link (5-link)",
      adaptiveDamping: "Yes (CCD)",
      airSuspension: "Yes (active air suspension)",
      seatMaterial: "Nappa leather",
      seatComfort: "Heated + ventilated + massage",
      rearSeatHeat: "Yes",
      rearSeatVent: "No",
      steeringHeat: "Yes",
      wirelessCharge: "Yes (dual 50W)",
      doorHandles: "Flush, powered e-latch",
      ambient: "Yes (RGB)",
      roof: "Panoramic glass + powered sunshade",
      display: '16" 3.5K mini-LED',
      cluster: '13" LCD instrument cluster',
      headUp: "Yes (36\" AR HUD)",
      audio: "Zeekr Sound Pro 21-spk (Dolby Atmos)",
      ncap: "5★ (Euro NCAP & ANCAP)",
      airbags: "7 airbags (incl. far-side)",
      aeb: "Standard",
      adaptiveCruise: "Standard (ACC + LCC)",
      laneKeep: "Standard",
      blindSpot: "Standard",
      camera360: "Standard",
      parkAssist: "Standard (auto park)",
      driverMonitor: "Yes (DMS)",
      adas: "Zeekr Assisted Drive (15 functions)",
      warranty: "Varies by market",
      batteryWarranty: "8 yr / 200,000 km",
    },
  },
  {
    id: "byd-sealion-7-base",
    brand: "BYD",
    model: "Sealion 7",
    trimShort: "Premium (Base)",
    accent: "#e23b3b",
    highlight: "Longest range of the Sealion 7 line, LFP Blade battery",
    specs: {
      price: 54990,
      segment: "Mid-size SUV",
      bodyStyle: "5-door SUV",
      trim: "Premium RWD",
      power: 230,
      powerHp: 313,
      torque: 380,
      accel: 6.7,
      topSpeed: 215,
      drive: "Rear-wheel drive",
      rangeWltp: 482,
      batteryUsable: 82.5,
      batteryType: "LFP (BYD Blade)",
      architecture: "400 V",
      dcMax: 150,
      dcTime: 32,
      acMax: 11,
      efficiency: 17.1,
      heatPump: "Yes",
      v2l: "Yes",
      length: 4830,
      width: 1925,
      height: 1620,
      wheelbase: 2930,
      boot: 520,
      bootMax: 1789,
      frunk: 58,
      seats: 5,
      kerbWeight: 2225,
      towing: 1500,
      wheels: '19" alloy',
      suspensionFront: "Double wishbone",
      suspensionRear: "Multi-link",
      adaptiveDamping: "No (frequency-selective passive)",
      airSuspension: "No",
      seatMaterial: "Synthetic leather",
      seatComfort: "Heated + ventilated (front)",
      rearSeatHeat: "No",
      rearSeatVent: "No",
      steeringHeat: "No",
      wirelessCharge: "Yes (50W)",
      doorHandles: "Flush (pop-out)",
      ambient: "Yes (RGB, 128-colour)",
      roof: "Panoramic glass roof",
      display: '15.6" rotating touchscreen',
      cluster: '10.25" digital cluster',
      headUp: "Yes (W-HUD)",
      audio: "12-speaker Dynaudio",
      ncap: "5★ ANCAP (2025)",
      airbags: "Front, side, curtain + far-side",
      aeb: "Standard",
      adaptiveCruise: "Standard",
      laneKeep: "Standard",
      blindSpot: "Standard",
      camera360: "Standard",
      parkAssist: "Standard (auto park)",
      driverMonitor: "Yes",
      adas: "BYD DiPilot (ADAS)",
      warranty: "6 yr / 150,000 km",
      batteryWarranty: "8 yr / 160,000 km",
    },
  },
  {
    id: "byd-sealion-7-performance",
    brand: "BYD",
    model: "Sealion 7",
    trimShort: "Performance AWD",
    accent: "#a11d1d",
    highlight: "390 kW dual-motor AWD with durable Blade battery",
    specs: {
      price: 63990,
      segment: "Mid-size SUV",
      bodyStyle: "5-door SUV",
      trim: "Performance AWD",
      power: 390,
      powerHp: 530,
      torque: 690,
      accel: 4.5,
      topSpeed: 215,
      drive: "All-wheel drive (dual motor)",
      rangeWltp: 456,
      batteryUsable: 82.5,
      batteryType: "LFP (BYD Blade)",
      architecture: "400 V",
      dcMax: 150,
      dcTime: 32,
      acMax: 11,
      efficiency: 18.1,
      heatPump: "Yes",
      v2l: "Yes",
      length: 4830,
      width: 1925,
      height: 1620,
      wheelbase: 2930,
      boot: 520,
      bootMax: 1789,
      frunk: 58,
      seats: 5,
      kerbWeight: 2340,
      towing: 1500,
      wheels: '20" alloy',
      suspensionFront: "Double wishbone",
      suspensionRear: "Multi-link",
      adaptiveDamping: "No (frequency-selective passive)",
      airSuspension: "No",
      seatMaterial: "Synthetic leather",
      seatComfort: "Heated + ventilated (front)",
      rearSeatHeat: "Yes",
      rearSeatVent: "No",
      steeringHeat: "Yes",
      wirelessCharge: "Yes (50W)",
      doorHandles: "Flush (pop-out)",
      ambient: "Yes (RGB, 128-colour)",
      roof: "Panoramic glass roof",
      display: '15.6" rotating touchscreen',
      cluster: '10.25" digital cluster',
      headUp: "Yes (W-HUD)",
      audio: "12-speaker Dynaudio",
      ncap: "5★ ANCAP (2025)",
      airbags: "Front, side, curtain + far-side",
      aeb: "Standard",
      adaptiveCruise: "Standard",
      laneKeep: "Standard",
      blindSpot: "Standard",
      camera360: "Standard",
      parkAssist: "Standard (auto park)",
      driverMonitor: "Yes",
      adas: "BYD DiPilot (ADAS)",
      warranty: "6 yr / 150,000 km",
      batteryWarranty: "8 yr / 160,000 km",
    },
  },
  {
    id: "tesla-model-y-rwd",
    brand: "Tesla",
    model: "Model Y",
    trimShort: "RWD",
    accent: "#8b5cf6",
    highlight: "Facelifted 'Juniper' RWD — efficient LFP with big cargo",
    specs: {
      price: 58900,
      segment: "Mid-size SUV",
      bodyStyle: "5-door SUV",
      trim: "RWD (Juniper MY25)",
      power: 220,
      powerHp: 295,
      torque: 420,
      accel: 5.9,
      topSpeed: 201,
      drive: "Rear-wheel drive",
      rangeWltp: 466,
      batteryUsable: 60,
      batteryType: "LFP",
      architecture: "400 V",
      dcMax: 175,
      dcTime: 27,
      acMax: 11,
      efficiency: 14.8,
      heatPump: "Yes",
      v2l: "No",
      length: 4797,
      width: 1982,
      height: 1624,
      wheelbase: 2890,
      boot: 822,
      bootMax: 2138,
      frunk: 117,
      seats: 5,
      kerbWeight: 1921,
      towing: 1600,
      wheels: '19" alloy',
      suspensionFront: "Double wishbone",
      suspensionRear: "Multi-link",
      adaptiveDamping: "No (revised passive, Juniper)",
      airSuspension: "No",
      seatMaterial: "Synthetic (vegan) leather",
      seatComfort: "Heated + ventilated (front)",
      rearSeatHeat: "Yes",
      rearSeatVent: "No",
      steeringHeat: "Yes",
      wirelessCharge: "Yes (2 pads)",
      doorHandles: "Flush (manual paddle inside)",
      ambient: "Yes (light bar)",
      roof: "Fixed panoramic glass",
      display: '15.4" central touchscreen',
      cluster: "None (central display) + 8\" rear screen",
      headUp: "No",
      audio: "9-speaker",
      ncap: "5★ Euro NCAP (2022)",
      airbags: "Front, side, curtain, knee",
      aeb: "Standard",
      adaptiveCruise: "Standard (Traffic-Aware)",
      laneKeep: "Standard (Autosteer)",
      blindSpot: "Standard (camera)",
      camera360: "No (camera feeds only)",
      parkAssist: "Standard (Autopark)",
      driverMonitor: "Yes (cabin camera)",
      adas: "Autopilot (ADAS); FSD optional",
      warranty: "5 yr / unlimited km",
      batteryWarranty: "8 yr / 160,000 km",
    },
  },
  {
    id: "tesla-model-y-long-range",
    brand: "Tesla",
    model: "Model Y",
    trimShort: "Long Range AWD",
    accent: "#6d28d9",
    highlight: "Dual-motor AWD, 551 km range and 250 kW DC charging",
    specs: {
      price: 68900,
      segment: "Mid-size SUV",
      bodyStyle: "5-door SUV",
      trim: "Long Range AWD (Juniper MY25)",
      power: 331,
      powerHp: 444,
      torque: 493,
      accel: 4.8,
      topSpeed: 201,
      drive: "All-wheel drive (dual motor)",
      rangeWltp: 551,
      batteryUsable: 75,
      batteryType: "NMC (lithium-ion)",
      architecture: "400 V",
      dcMax: 250,
      dcTime: 27,
      acMax: 11,
      efficiency: 15.6,
      heatPump: "Yes",
      v2l: "No",
      length: 4797,
      width: 1982,
      height: 1624,
      wheelbase: 2890,
      boot: 822,
      bootMax: 2138,
      frunk: 117,
      seats: 5,
      kerbWeight: 1997,
      towing: 1600,
      wheels: '19" alloy',
      suspensionFront: "Double wishbone",
      suspensionRear: "Multi-link",
      adaptiveDamping: "No (revised passive, Juniper)",
      airSuspension: "No",
      seatMaterial: "Synthetic (vegan) leather",
      seatComfort: "Heated + ventilated (front)",
      rearSeatHeat: "Yes",
      rearSeatVent: "No",
      steeringHeat: "Yes",
      wirelessCharge: "Yes (2 pads)",
      doorHandles: "Flush (manual paddle inside)",
      ambient: "Yes (light bar)",
      roof: "Fixed panoramic glass",
      display: '15.4" central touchscreen',
      cluster: "None (central display) + 8\" rear screen",
      headUp: "No",
      audio: "17-speaker + 2 subs (immersive)",
      ncap: "5★ Euro NCAP (2022)",
      airbags: "Front, side, curtain, knee",
      aeb: "Standard",
      adaptiveCruise: "Standard (Traffic-Aware)",
      laneKeep: "Standard (Autosteer)",
      blindSpot: "Standard (camera)",
      camera360: "No (camera feeds only)",
      parkAssist: "Standard (Autopark)",
      driverMonitor: "Yes (cabin camera)",
      adas: "Autopilot (ADAS); FSD optional",
      warranty: "5 yr / unlimited km",
      batteryWarranty: "8 yr / 192,000 km",
    },
  },
  {
    id: "mercedes-eqa-250plus",
    brand: "Mercedes-Benz",
    model: "EQA 250+",
    trimShort: "250+ (FWD)",
    accent: "#5b7083",
    highlight: "Compact premium SUV; efficient FWD with 560 km range",
    specs: {
      price: 84900,
      segment: "Compact SUV",
      bodyStyle: "5-door SUV",
      trim: "250+ FWD",
      power: 140,
      powerHp: 190,
      torque: 385,
      accel: 8.6,
      topSpeed: 160,
      drive: "Front-wheel drive",
      rangeWltp: 560,
      batteryUsable: 70.5,
      batteryType: "NMC (lithium-ion)",
      architecture: "400 V",
      dcMax: 100,
      dcTime: 32,
      acMax: 11,
      efficiency: 14.4,
      heatPump: "Yes",
      v2l: "No",
      length: 4463,
      width: 1834,
      height: 1620,
      wheelbase: 2729,
      boot: 340,
      bootMax: 1320,
      frunk: 0,
      seats: 5,
      kerbWeight: 2045,
      towing: 1500,
      wheels: '18" alloy',
      suspensionFront: "MacPherson strut",
      suspensionRear: "Multi-link (4-link)",
      adaptiveDamping: "Optional",
      airSuspension: "No",
      seatMaterial: "Artico synthetic leather",
      seatComfort: "Heated (front); ventilation optional",
      rearSeatHeat: "Optional",
      rearSeatVent: "No",
      steeringHeat: "Optional",
      wirelessCharge: "Yes",
      doorHandles: "Conventional grip",
      ambient: "Yes (64-colour)",
      roof: "Panoramic glass (optional)",
      display: 'Dual 10.25" MBUX displays',
      cluster: '10.25" digital cluster',
      headUp: "Optional",
      audio: "10-spk; Burmester 12-spk opt.",
      ncap: "5★ Euro NCAP (2019)",
      airbags: "7 airbags (incl. knee)",
      aeb: "Standard",
      adaptiveCruise: "Optional (Distronic)",
      laneKeep: "Standard (active)",
      blindSpot: "Standard (active)",
      camera360: "Optional",
      parkAssist: "Standard (Parktronic)",
      driverMonitor: "Yes (Attention Assist)",
      adas: "Driving Assistance (ADAS)",
      warranty: "5 yr / unlimited km",
      batteryWarranty: "8 yr / 160,000 km",
    },
  },
  {
    id: "bmw-ix1-xdrive30",
    brand: "BMW",
    model: "iX1",
    trimShort: "xDrive30",
    accent: "#16a0c8",
    highlight: "Premium German build & badge; compact dual-motor AWD",
    specs: {
      price: 84900,
      segment: "Compact / subcompact SUV",
      bodyStyle: "5-door SUV",
      trim: "xDrive30",
      power: 230,
      powerHp: 313,
      torque: 494,
      accel: 5.6,
      topSpeed: 180,
      drive: "All-wheel drive (dual motor)",
      rangeWltp: 440,
      batteryUsable: 64.7,
      batteryType: "NMC (lithium-ion)",
      architecture: "400 V",
      dcMax: 130,
      dcTime: 29,
      acMax: 22,
      efficiency: 16.8,
      heatPump: "Yes",
      v2l: "No",
      length: 4500,
      width: 1845,
      height: 1616,
      wheelbase: 2692,
      boot: 490,
      bootMax: 1495,
      frunk: 0,
      seats: 5,
      kerbWeight: 2010,
      towing: 1200,
      wheels: '18" alloy (std)',
      suspensionFront: "Single-joint strut",
      suspensionRear: "Multi-link (3-link)",
      adaptiveDamping: "Optional (Adaptive M)",
      airSuspension: "No",
      seatMaterial: "Sensatec (synthetic)",
      seatComfort: "Heated (front); ventilation optional",
      rearSeatHeat: "Optional",
      rearSeatVent: "No",
      steeringHeat: "Optional",
      wirelessCharge: "Yes",
      doorHandles: "Conventional grip",
      ambient: "Yes",
      roof: "Panoramic glass (optional)",
      display: '10.7" curved touchscreen',
      cluster: '10.25" curved display',
      headUp: "Optional",
      audio: "6-spk std; Harman Kardon 12-spk opt.",
      ncap: "5★ Euro NCAP (2022)",
      airbags: "6 airbags + centre airbag",
      aeb: "Standard",
      adaptiveCruise: "Standard",
      laneKeep: "Standard",
      blindSpot: "Optional",
      camera360: "Optional (Parking Assistant Plus)",
      parkAssist: "Standard",
      driverMonitor: "Yes (Attention Assistant)",
      adas: "Driving Assistant (ADAS)",
      warranty: "3 yr / unlimited km",
      batteryWarranty: "8 yr / 160,000 km",
    },
  },
  {
    id: "audi-q6-etron-quattro",
    brand: "Audi",
    model: "Q6 e-tron",
    trimShort: "quattro",
    accent: "#d97706",
    highlight: "800V PPE platform — 625 km range and 270 kW charging",
    specs: {
      price: 99900,
      segment: "Mid-size SUV",
      bodyStyle: "5-door SUV",
      trim: "e-tron quattro",
      power: 285,
      powerHp: 387,
      torque: 855,
      accel: 5.9,
      topSpeed: 210,
      drive: "All-wheel drive (quattro)",
      rangeWltp: 625,
      batteryUsable: 94.9,
      batteryType: "NMC (lithium-ion)",
      architecture: "800 V",
      dcMax: 270,
      dcTime: 21,
      acMax: 11,
      efficiency: 15.2,
      heatPump: "Yes",
      v2l: "No",
      length: 4771,
      width: 1939,
      height: 1685,
      wheelbase: 2899,
      boot: 526,
      bootMax: 1529,
      frunk: 64,
      seats: 5,
      kerbWeight: 2345,
      towing: 2400,
      wheels: '19" alloy',
      suspensionFront: "5-link",
      suspensionRear: "5-link",
      adaptiveDamping: "Optional",
      airSuspension: "Optional (adaptive air)",
      seatMaterial: "Synthetic leather / cloth",
      seatComfort: "Heated (front); ventilation optional",
      rearSeatHeat: "Optional",
      rearSeatVent: "No",
      steeringHeat: "Optional",
      wirelessCharge: "Yes",
      doorHandles: "Recessed (flush optional)",
      ambient: "Yes (RGB interior light)",
      roof: "Panoramic glass (optional)",
      display: '11.9" + 14.5" curved MMI',
      cluster: '11.9" Audi virtual cockpit',
      headUp: "Optional (AR HUD)",
      audio: "10-spk; B&O 3D opt.",
      ncap: "5★ Euro NCAP (2024)",
      airbags: "8 airbags (incl. centre)",
      aeb: "Standard",
      adaptiveCruise: "Standard",
      laneKeep: "Standard",
      blindSpot: "Optional (side assist)",
      camera360: "Optional",
      parkAssist: "Standard",
      driverMonitor: "Yes (rest recommendation)",
      adas: "Adaptive driving assist (ADAS)",
      warranty: "5 yr / unlimited km",
      batteryWarranty: "8 yr / 160,000 km",
    },
  },
];

// Left-to-right display order for the cards and comparison columns.
// Edit this list to reorder; unknown ids fall back to the front.
const VEHICLE_ORDER = [
  "zeekr-7x-base",
  "zeekr-7x-long-range",
  "zeekr-7x-performance",
  "byd-sealion-7-base",
  "byd-sealion-7-performance",
  "tesla-model-y-rwd",
  "tesla-model-y-long-range",
  "audi-q6-etron-quattro",
  "bmw-ix1-xdrive30",
  "mercedes-eqa-250plus",
];
VEHICLES.sort(
  (a, b) => VEHICLE_ORDER.indexOf(a.id) - VEHICLE_ORDER.indexOf(b.id)
);

if (typeof module !== "undefined" && module.exports) {
  module.exports = { VEHICLES, SPEC_GROUPS, CURRENCY };
}
