/**
 * EV comparison dataset.
 *
 * Figures are manufacturer / WLTP claims gathered from public sources
 * (manufacturer sites, EV-Database, zecar, EVKX) as of mid-2025.
 * Prices are indicative Australian RRP (AUD, before on-road costs) so that
 * every model can be compared on a like-for-like basis; local pricing,
 * range and equipment vary by market. Verify before purchase.
 *
 * `better` tells the UI which direction is "best" for numeric highlighting:
 *   'high' -> larger value wins, 'low' -> smaller value wins, null -> no winner.
 */

const CURRENCY = "AUD";

const SPEC_GROUPS = [
  {
    title: "Pricing & Positioning",
    rows: [
      { key: "price", label: "Indicative price (RRP)", unit: CURRENCY, better: "low", format: "currency" },
      { key: "segment", label: "Segment", better: null },
      { key: "bodyStyle", label: "Body style", better: null },
      { key: "trim", label: "Trim / grade", better: null },
    ],
  },
  {
    title: "Performance",
    rows: [
      { key: "power", label: "Peak power", unit: "kW", better: "high" },
      { key: "powerHp", label: "Peak power", unit: "hp", better: "high" },
      { key: "torque", label: "Peak torque", unit: "Nm", better: "high" },
      { key: "accel", label: "0–100 km/h", unit: "s", better: "low" },
      { key: "topSpeed", label: "Top speed", unit: "km/h", better: "high" },
      { key: "drive", label: "Drivetrain", better: null },
    ],
  },
  {
    title: "Battery, Range & Charging",
    rows: [
      { key: "rangeWltp", label: "Range (WLTP)", unit: "km", better: "high" },
      { key: "batteryUsable", label: "Usable battery", unit: "kWh", better: "high" },
      { key: "batteryType", label: "Battery chemistry", better: null },
      { key: "architecture", label: "Electrical architecture", better: null },
      { key: "dcMax", label: "Max DC charging", unit: "kW", better: "high" },
      { key: "dcTime", label: "DC 10–80%", unit: "min", better: "low" },
      { key: "acMax", label: "Max AC charging", unit: "kW", better: "high" },
      { key: "efficiency", label: "Efficiency (WLTP)", unit: "kWh/100km", better: "low" },
      { key: "v2l", label: "Vehicle-to-load (V2L)", better: null },
    ],
  },
  {
    title: "Dimensions & Practicality",
    rows: [
      { key: "length", label: "Length", unit: "mm", better: null },
      { key: "width", label: "Width (excl. mirrors)", unit: "mm", better: null },
      { key: "height", label: "Height", unit: "mm", better: null },
      { key: "wheelbase", label: "Wheelbase", unit: "mm", better: "high" },
      { key: "boot", label: "Boot (rear)", unit: "L", better: "high" },
      { key: "bootMax", label: "Boot (seats folded)", unit: "L", better: "high" },
      { key: "frunk", label: "Frunk", unit: "L", better: "high" },
      { key: "seats", label: "Seats", better: null },
      { key: "kerbWeight", label: "Kerb weight", unit: "kg", better: "low" },
      { key: "towing", label: "Towing (braked)", unit: "kg", better: "high" },
      { key: "wheels", label: "Wheels", better: null },
    ],
  },
  {
    title: "Comfort & Technology",
    rows: [
      { key: "airSuspension", label: "Air suspension", better: null },
      { key: "seatMaterial", label: "Seat material", better: null },
      { key: "seatComfort", label: "Heated / ventilated / massage", better: null },
      { key: "display", label: "Central display", better: null },
      { key: "cluster", label: "Driver display / HUD", better: null },
      { key: "roof", label: "Roof", better: null },
      { key: "adas", label: "Driver assistance", better: null },
      { key: "warranty", label: "Vehicle warranty", better: null },
      { key: "batteryWarranty", label: "Battery warranty", better: null },
    ],
  },
];

const VEHICLES = [
  {
    id: "zeekr-7x-base",
    brand: "Zeekr",
    model: "7X",
    trimShort: "RWD (Base)",
    accent: "#2b7fff",
    highlight: "Value-focused long-range SUV on an 800V platform",
    specs: {
      price: 57900,
      segment: "Mid-size SUV",
      bodyStyle: "5-door SUV",
      trim: "Core RWD",
      power: 310,
      powerHp: 421,
      torque: 440,
      accel: 6.0,
      topSpeed: 210,
      drive: "Rear-wheel drive",
      rangeWltp: 480,
      batteryUsable: 71,
      batteryType: "NMC (lithium-ion)",
      architecture: "800 V",
      dcMax: 480,
      dcTime: 13,
      acMax: 22,
      efficiency: 17.8,
      v2l: "Yes (3.3 kW)",
      length: 4787,
      width: 1930,
      height: 1650,
      wheelbase: 2900,
      boot: 539,
      bootMax: 1978,
      frunk: 42,
      seats: 5,
      kerbWeight: 2380,
      towing: 2000,
      wheels: '19" alloy',
      airSuspension: "No",
      seatMaterial: "Textile & PU",
      seatComfort: "Heated (front)",
      display: '16" 3.5K mini-LED',
      cluster: '13" LCD instrument cluster',
      roof: "Panoramic glass + powered sunshade",
      adas: "Zeekr Assisted Drive (ADAS)",
      warranty: "Varies by market",
      batteryWarranty: "8 yr / 200,000 km",
    },
  },
  {
    id: "zeekr-7x-long-range",
    brand: "Zeekr",
    model: "7X",
    trimShort: "Long Range RWD",
    accent: "#1b6ef3",
    highlight: "Longest-range Zeekr — 615 km from 100 kWh on 800V",
    specs: {
      price: 63900,
      segment: "Mid-size SUV",
      bodyStyle: "5-door SUV",
      trim: "Long Range RWD",
      power: 310,
      powerHp: 421,
      torque: 440,
      accel: 6.0,
      topSpeed: 210,
      drive: "Rear-wheel drive",
      rangeWltp: 615,
      batteryUsable: 95,
      batteryType: "NMC (lithium-ion)",
      architecture: "800 V",
      dcMax: 480,
      dcTime: 16,
      acMax: 22,
      efficiency: 17.7,
      v2l: "Yes (3.3 kW)",
      length: 4787,
      width: 1930,
      height: 1650,
      wheelbase: 2900,
      boot: 539,
      bootMax: 1978,
      frunk: 42,
      seats: 5,
      kerbWeight: 2415,
      towing: 2000,
      wheels: '19" alloy',
      airSuspension: "No",
      seatMaterial: "Textile & PU",
      seatComfort: "Heated + ventilated + massage",
      display: '16" 3.5K mini-LED',
      cluster: '13" LCD instrument cluster',
      roof: "Panoramic glass + powered sunshade",
      adas: "Zeekr Assisted Drive (ADAS)",
      warranty: "Varies by market",
      batteryWarranty: "8 yr / 200,000 km",
    },
  },
  {
    id: "zeekr-7x-performance",
    brand: "Zeekr",
    model: "7X",
    trimShort: "Performance AWD",
    accent: "#0b3ea8",
    highlight: "Quickest here — 470 kW dual-motor with air suspension",
    specs: {
      price: 72900,
      segment: "Mid-size SUV",
      bodyStyle: "5-door SUV",
      trim: "Privilege AWD",
      power: 470,
      powerHp: 639,
      torque: 710,
      accel: 3.8,
      topSpeed: 210,
      drive: "All-wheel drive (dual motor)",
      rangeWltp: 543,
      batteryUsable: 95,
      batteryType: "NMC (CATL Qilin)",
      architecture: "800 V",
      dcMax: 480,
      dcTime: 16,
      acMax: 22,
      efficiency: 19.9,
      v2l: "Yes (3.3 kW)",
      length: 4787,
      width: 1930,
      height: 1650,
      wheelbase: 2900,
      boot: 539,
      bootMax: 1978,
      frunk: 42,
      seats: 5,
      kerbWeight: 2535,
      towing: 2000,
      wheels: '21" alloy',
      airSuspension: "Yes (active air suspension)",
      seatMaterial: "Nappa leather",
      seatComfort: "Heated + ventilated + massage",
      display: '16" 3.5K mini-LED',
      cluster: '13" LCD instrument cluster',
      roof: "Panoramic glass + powered sunshade",
      adas: "Zeekr Assisted Drive (ADAS)",
      warranty: "Varies by market",
      batteryWarranty: "8 yr / 200,000 km",
    },
  },
  {
    id: "byd-sealion-7-base",
    brand: "BYD",
    model: "Sealion 7",
    trimShort: "Premium (Base)",
    accent: "#e23b3b",
    highlight: "Longest range of the Sealion 7 line, LFP Blade battery",
    specs: {
      price: 54990,
      segment: "Mid-size SUV",
      bodyStyle: "5-door SUV",
      trim: "Premium RWD",
      power: 230,
      powerHp: 313,
      torque: 380,
      accel: 6.7,
      topSpeed: 215,
      drive: "Rear-wheel drive",
      rangeWltp: 482,
      batteryUsable: 82.5,
      batteryType: "LFP (BYD Blade)",
      architecture: "400 V",
      dcMax: 150,
      dcTime: 32,
      acMax: 11,
      efficiency: 17.1,
      v2l: "Yes",
      length: 4830,
      width: 1925,
      height: 1620,
      wheelbase: 2930,
      boot: 520,
      bootMax: 1789,
      frunk: 58,
      seats: 5,
      kerbWeight: 2225,
      towing: 1500,
      wheels: '19" alloy',
      airSuspension: "No",
      seatMaterial: "Synthetic leather",
      seatComfort: "Heated + ventilated (front)",
      display: '15.6" rotating touchscreen',
      cluster: '10.25" cluster + HUD',
      roof: "Panoramic glass roof",
      adas: "BYD DiPilot (ADAS)",
      warranty: "6 yr / 150,000 km",
      batteryWarranty: "8 yr / 160,000 km",
    },
  },
  {
    id: "byd-sealion-7-performance",
    brand: "BYD",
    model: "Sealion 7",
    trimShort: "Performance AWD",
    accent: "#a11d1d",
    highlight: "390 kW dual-motor AWD with durable Blade battery",
    specs: {
      price: 63990,
      segment: "Mid-size SUV",
      bodyStyle: "5-door SUV",
      trim: "Performance AWD",
      power: 390,
      powerHp: 530,
      torque: 690,
      accel: 4.5,
      topSpeed: 215,
      drive: "All-wheel drive (dual motor)",
      rangeWltp: 456,
      batteryUsable: 82.5,
      batteryType: "LFP (BYD Blade)",
      architecture: "400 V",
      dcMax: 150,
      dcTime: 32,
      acMax: 11,
      efficiency: 18.1,
      v2l: "Yes",
      length: 4830,
      width: 1925,
      height: 1620,
      wheelbase: 2930,
      boot: 520,
      bootMax: 1789,
      frunk: 58,
      seats: 5,
      kerbWeight: 2340,
      towing: 1500,
      wheels: '20" alloy',
      airSuspension: "No",
      seatMaterial: "Synthetic leather",
      seatComfort: "Heated + ventilated (front)",
      display: '15.6" rotating touchscreen',
      cluster: '10.25" cluster + HUD',
      roof: "Panoramic glass roof",
      adas: "BYD DiPilot (ADAS)",
      warranty: "6 yr / 150,000 km",
      batteryWarranty: "8 yr / 160,000 km",
    },
  },
  {
    id: "bmw-ix1-xdrive30",
    brand: "BMW",
    model: "iX1",
    trimShort: "xDrive30",
    accent: "#16a0c8",
    highlight: "Premium German build & badge; compact dual-motor AWD",
    specs: {
      price: 84900,
      segment: "Compact / subcompact SUV",
      bodyStyle: "5-door SUV",
      trim: "xDrive30",
      power: 230,
      powerHp: 313,
      torque: 494,
      accel: 5.6,
      topSpeed: 180,
      drive: "All-wheel drive (dual motor)",
      rangeWltp: 440,
      batteryUsable: 64.7,
      batteryType: "NMC (lithium-ion)",
      architecture: "400 V",
      dcMax: 130,
      dcTime: 29,
      acMax: 22,
      efficiency: 16.8,
      v2l: "No",
      length: 4500,
      width: 1845,
      height: 1616,
      wheelbase: 2692,
      boot: 490,
      bootMax: 1495,
      frunk: 0,
      seats: 5,
      kerbWeight: 2010,
      towing: 1200,
      wheels: '18" alloy (std)',
      airSuspension: "No",
      seatMaterial: "Sensatec (synthetic)",
      seatComfort: "Heated (front, optional)",
      display: '10.7" curved touchscreen',
      cluster: '10.25" curved display',
      roof: "Panoramic glass (optional)",
      adas: "Driving Assistant (ADAS)",
      warranty: "3 yr / unlimited km",
      batteryWarranty: "8 yr / 160,000 km",
    },
  },
  {
    id: "tesla-model-y-rwd",
    brand: "Tesla",
    model: "Model Y",
    trimShort: "RWD",
    accent: "#8b5cf6",
    highlight: "Facelifted 'Juniper' RWD — efficient LFP with big cargo",
    specs: {
      price: 58900,
      segment: "Mid-size SUV",
      bodyStyle: "5-door SUV",
      trim: "RWD (Juniper MY25)",
      power: 220,
      powerHp: 295,
      torque: 420,
      accel: 5.9,
      topSpeed: 201,
      drive: "Rear-wheel drive",
      rangeWltp: 466,
      batteryUsable: 60,
      batteryType: "LFP",
      architecture: "400 V",
      dcMax: 175,
      dcTime: 27,
      acMax: 11,
      efficiency: 14.8,
      v2l: "No",
      length: 4797,
      width: 1982,
      height: 1624,
      wheelbase: 2890,
      boot: 822,
      bootMax: 2138,
      frunk: 117,
      seats: 5,
      kerbWeight: 1921,
      towing: 1600,
      wheels: '19" alloy',
      airSuspension: "No",
      seatMaterial: "Synthetic (vegan) leather",
      seatComfort: "Heated + ventilated (front)",
      display: '15.4" central touchscreen',
      cluster: "None (central display) + 8\" rear screen",
      roof: "Fixed panoramic glass",
      adas: "Autopilot (ADAS); FSD optional",
      warranty: "5 yr / unlimited km",
      batteryWarranty: "8 yr / 160,000 km",
    },
  },
  {
    id: "tesla-model-y-long-range",
    brand: "Tesla",
    model: "Model Y",
    trimShort: "Long Range AWD",
    accent: "#6d28d9",
    highlight: "Dual-motor AWD, 551 km range and 250 kW DC charging",
    specs: {
      price: 68900,
      segment: "Mid-size SUV",
      bodyStyle: "5-door SUV",
      trim: "Long Range AWD (Juniper MY25)",
      power: 331,
      powerHp: 444,
      torque: 493,
      accel: 4.8,
      topSpeed: 201,
      drive: "All-wheel drive (dual motor)",
      rangeWltp: 551,
      batteryUsable: 75,
      batteryType: "NMC (lithium-ion)",
      architecture: "400 V",
      dcMax: 250,
      dcTime: 27,
      acMax: 11,
      efficiency: 15.6,
      v2l: "No",
      length: 4797,
      width: 1982,
      height: 1624,
      wheelbase: 2890,
      boot: 822,
      bootMax: 2138,
      frunk: 117,
      seats: 5,
      kerbWeight: 1997,
      towing: 1600,
      wheels: '19" alloy',
      airSuspension: "No",
      seatMaterial: "Synthetic (vegan) leather",
      seatComfort: "Heated + ventilated (front) + heated rear",
      display: '15.4" central touchscreen',
      cluster: "None (central display) + 8\" rear screen",
      roof: "Fixed panoramic glass",
      adas: "Autopilot (ADAS); FSD optional",
      warranty: "5 yr / unlimited km",
      batteryWarranty: "8 yr / 192,000 km",
    },
  },
  {
    id: "mercedes-eqa-250plus",
    brand: "Mercedes-Benz",
    model: "EQA 250+",
    trimShort: "250+ (FWD)",
    accent: "#5b7083",
    highlight: "Compact premium SUV; efficient FWD with 560 km range",
    specs: {
      price: 84900,
      segment: "Compact SUV",
      bodyStyle: "5-door SUV",
      trim: "250+ FWD",
      power: 140,
      powerHp: 190,
      torque: 385,
      accel: 8.6,
      topSpeed: 160,
      drive: "Front-wheel drive",
      rangeWltp: 560,
      batteryUsable: 70.5,
      batteryType: "NMC (lithium-ion)",
      architecture: "400 V",
      dcMax: 100,
      dcTime: 32,
      acMax: 11,
      efficiency: 14.4,
      v2l: "No",
      length: 4463,
      width: 1834,
      height: 1620,
      wheelbase: 2729,
      boot: 340,
      bootMax: 1320,
      frunk: 0,
      seats: 5,
      kerbWeight: 2045,
      towing: 1500,
      wheels: '18" alloy',
      airSuspension: "No",
      seatMaterial: "Artico synthetic leather",
      seatComfort: "Heated (front); ventilation optional",
      display: 'Dual 10.25" MBUX displays',
      cluster: '10.25" digital cluster',
      roof: "Panoramic glass (optional)",
      adas: "Driving Assistance package (ADAS)",
      warranty: "5 yr / unlimited km",
      batteryWarranty: "8 yr / 160,000 km",
    },
  },
  {
    id: "audi-q6-etron-quattro",
    brand: "Audi",
    model: "Q6 e-tron",
    trimShort: "quattro",
    accent: "#d97706",
    highlight: "800V PPE platform — 625 km range and 270 kW charging",
    specs: {
      price: 99900,
      segment: "Mid-size SUV",
      bodyStyle: "5-door SUV",
      trim: "e-tron quattro",
      power: 285,
      powerHp: 387,
      torque: 855,
      accel: 5.9,
      topSpeed: 210,
      drive: "All-wheel drive (quattro)",
      rangeWltp: 625,
      batteryUsable: 94.9,
      batteryType: "NMC (lithium-ion)",
      architecture: "800 V",
      dcMax: 270,
      dcTime: 21,
      acMax: 11,
      efficiency: 15.2,
      v2l: "No",
      length: 4771,
      width: 1939,
      height: 1685,
      wheelbase: 2899,
      boot: 526,
      bootMax: 1529,
      frunk: 64,
      seats: 5,
      kerbWeight: 2345,
      towing: 2400,
      wheels: '19" alloy',
      airSuspension: "Optional (adaptive air)",
      seatMaterial: "Synthetic leather / cloth",
      seatComfort: "Heated (front); ventilation optional",
      display: '11.9" + 14.5" curved MMI',
      cluster: '11.9" Audi virtual cockpit',
      roof: "Panoramic glass (optional)",
      adas: "Adaptive driving assist (ADAS)",
      warranty: "5 yr / unlimited km",
      batteryWarranty: "8 yr / 160,000 km",
    },
  },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { VEHICLES, SPEC_GROUPS, CURRENCY };
}
